title: Oliver Jiang
author: ogelsir
subtitle: Hello, World!

url: "http://oliverjiang.me"
baseurl: ""

footer_only_homepage: false
footer_url: "oliverjiang.me"
footer_text: "This is footer text."

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico
